language: python
matrix:
  include:
  - os: linux
    python: 3.6
    env: TOXENV=py36
  - os: linux
    python: 3.5
    env: TOXENV=py35
  - os: linux
    python: 3.4
    env: TOXENV=py34
  - os: linux
    python: 2.7
    env: TOXENV=py27
  - os: osx
    language: generic
    env:
      - PYTHON='3.7.0'
      - TOXENV=py37
  - os: osx
    language: generic
    env:
      - PYTHON='3.6.2'
      - TOXENV=py36
  - os: osx
    language: generic
    env:
      - PYTHON='3.5.2'
      - TOXENV=py35
  - os: osx
    language: generic
    env:
      - PYTHON='3.4.6'
      - TOXENV=py34
  - os: osx
    language: generic
    env:
      - PYTHON='2.7.13'
      - TOXENV=py27

install:
  - pip install tox
  - pip install cython
  - pip install pytest

script:
- ./update_cpp.sh
- ./.travis/run tox

deploy:
  provider: pypi
  user: "supercoderhawk"
  password:
    secure: "Your encrypted password"
  on:
    tag: true
