language: python
matrix:
  include:
  - os: linux
    python: 3.6
    env: TOXENV=py36
  - os: linux
    python: 3.5
    env: TOXENV=py35
  - os: linux
    python: 3.4
    env: TOXENV=py34
  - os: linux
    python: 2.7
    env: TOXENV=py27
install:
- pip install tox
- pip install cython
- pip install pytest
script:
- "./update_cpp.sh"
- tox
deploy:
  provider: pypi
  user: supercoderhawk
  password:
    secure: hDK22rP/Slc02QEQ4MGYUCT6LifPsY6UytKX0BCOTd992iVxz3ZicNN/93NFKtkZaFRt7Z1OOgPRxhYR3KwzC8aD6J8mNmd+56m0m10C/ss1zAK8oeFnI1qRWInzOfLbAwsTFxbfFhx6qRR1J4zZCuiqfyY0uKNKHGo+46x83ANSnw1u8oHRXVMGFoOgXhpprP/BLpLdloIa4ibnRxtpwalujl08Qf6kLz3W/38pUbbank/oEoRmt+ywebbM19aTfHkoaLnqTpKsn7znKXkBVY9SN73jsZ8IW6/85KNbM8OPlpJaWhBWUfD7nqGl3Uk3aT9WuDyxCUziaT5L0ZGbI4IvE8JxYqwgIKCVgFbe2r2ZrpxolQe2OfAmu8y+4pjdIN1VG22pDPXO49UnBHqYyRLi1jgO9QyMgQr0SYSksvv3UgCqaPfmKGTosHhxf/A04pVkbGIeAVCaao2oDly8bB8VL86LL2mCEFk7nl0EdrfnAbo9CnhwkC2/Ha0kp3xTOkP1CBA66ZRVcZozQEnQs8q0IuVF4wLy7D6Aj5vRwotqmVGyqUREVpuDrrPPgmExjDebBXTNUuCSqCnE8uLs3Hc9+m6fcLt5JV8pN00WOZxYea9fr+GVgEnQ0iBcJobYmiOpLGCJl56V741bt//Yw35UxBcpt2GJB9awyM21eFI=
  on:
    tag: true
