language: python
matrix:
  include:
  - os: linux
    python: 3.6
    env: TOXENV=py36
  - os: linux
    python: 3.5
    env: TOXENV=py35
  - os: linux
    python: 3.4
    env: TOXENV=py34
  - os: linux
    python: 2.7
    env: TOXENV=py27
install:
- pip install tox
- pip install cython
- pip install pytest
script:
- "./update_cpp.sh"
- tox
deploy:
  provider: pypi
  user: supercoderhawk
  password:
    secure: OctCC89SGzwmMyM8MDA6N9Te4YUCcX203gVtdI/3zBJMnMxzOAVhp7rTCUCunddw4n8jyEsRoA+bbnk4hSSRJrgvSux6HlC5uYPBhuvGqeRfVI5cE0rYRdYr0e/3e40px877f9LkFT+L9PTD1rCKLgMARLW7RW70BDxPvFKiFVU03DUM6IxwEvLZFMaJQRTwYbcBgj/40lb6YDXshCwvPjRn1J9E8Fs6SpCU/8yUmA/Bg+w24csSizmH/3vn1rXrcX8dhTDrOhL0ozQo7NR9j4II4gxtmQxqr6j3g+317iCLRn9uGutncuRQhIlgpOTk/eY7LIKwz/NY3zZx0XwQm16o/UKM4pGbkXlN0WgR0Du2034G3vPJKKFsVHuCxs6UtKck8q/2e/xG5k+YmSpV1YZ/Lrd5yrJ8OB1+LOQBtu4BB0ycaG32IhRcQf+CvEwln6fEk2j+ykkCag9X3Hr8z5bADpsvFIS96JBUFVGzyd/axSfCK292y5RQNh0St1Zit3a9YTUe7Um2iVWQqo8/Ty9PLLhNtQ0vXB3bQULFImaITRmWXv7DNMyrk2UofXmsVuDmEsAtd5hQzsJHRnTSpT/Pg6/jt4q6nKU5Xp8x14Myxx4hdddlc1J4vcR9CICIS5JjefkUwOuSNrXFq5HY04ZsoMMvyR0+zSbC/EMtDf8=
  on:
    tag: true
  skip_existing: true
