environment:
  password:
    secure: +2PzAF87OA3oqbs3LgG1TQ==
  os: Visual Studio 2017

  matrix:
    - python : 27
    - python : 27-x64
    - python : 34
    - python : 34-x64
    - python : 35	
    - python : 35-x64
    - python : 36	
    - python : 36-x64
    - python : 37	
    - python : 37-x64    

install:
  - git submodule update --init --recursive
  - pip install cython argparse pytest
  - update_cpp.sh
  - pip install -e .

build: false

test_script:
  - py.test tests --doctest-modules

on_success:
  - echo Build succesful!

deploy_script:
  - echo [distutils]                                  > %USERPROFILE%\\.pypirc
  - echo index-servers =                             >> %USERPROFILE%\\.pypirc
  - echo     pypi                                    >> %USERPROFILE%\\.pypirc
  - echo [pypi]                                      >> %USERPROFILE%\\.pypirc
  - echo username=supercoderhawk                     >> %USERPROFILE%\\.pypirc
  - echo password=%password%                         >> %USERPROFILE%\\.pypirc
  - set HOME=%USERPROFILE%
  - pip install wheel twine
  - ps: if($env:APPVEYOR_REPO_TAG -eq $TRUE) { python -W ignore setup.py bdist_wheel bdist_egg; twine upload dist/* }

deploy : on
